# Generated by Django 2.2.7 on 2020-02-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=50)),
                ('mobileno', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
